### ISSUE TITLE
FreeBSD 13.0 Quandary 

### ISSUE THREAD

**Issue by schijtreiger** [mrclksr/DSBLogoutmgr#1]
Hello,
First off: I have literally waited, wished & desperately searched decades for somebody to come up with an elegant lock/logout/reboot/shutdown applet that I could actually agree with. My loyalty & preference for fast, light and responsive DMs / WMs has kept me a FluxBox and OpenBox user, pretty much permanently. I still have to laugh when I can cold boot a FreeBSD installation on an NVMe SSD to full desktop interaction in about 7 seconds.
So you can imagine my delight when I came across your efforts. It was purely by chance whilst I was looking through some of vermade's site for some hints and tips. (shameless plug: https://vermaden.wordpress.com/). NomadBSD is also world class!

I find myself in a bit of a quagmire however. Installing DSBLogoutmgr by either pkg or building from ports on FreeBSD 11.0 11.1 11.2 12.0 goes without issue, and works perfectly every time. In the interest of testing to see if I am imagining things or not: I have done clean installs of all FreeBSD 11.x  12.x releases specifically, with a minimal Xorg desktop (FluxBox & OpenBox, users added to the operator / wheel groups etc) and all the requirements (Qt5, qt5ct etc) to run DSBLogoutmgr. This works perfectly every time, and DSBLogoutmgr (with all configs set) works as expected each time.

The pain in my ass starts with FreeBSD 13.0. Installing from pkg or from ports goes without any issues at all. I can launch DSBLogoutmgr just fine, it doesn't throw any errors at the console...until it is time to perform an action; by either direct button click or by the timer. It core-dumps every time. The core dump itself offer little in the way of indicating what may by the issue. I've analyzed the core dump with the FreeBSD debugger, and although I am no expert at this sort of thing, I am somewhat capable of understanding at least some obvious things any core dump may hint at. In the case of dsblogoutmgr.core however, I can't spot anything that would indicate the reason for the crash.
Are there any known issues with FreeBSD 13.0 & the Qt5 implementation that indicate why this might be? I've snouted around a bit in the UPDATING (in /user/src/ and /usr/ports/) files for the -CURRENT branch, but find no mention of any potential Qt5 issues.
Any hints will be greatly appreciated, I can also provide the actual dump file if needed.

**Comment by mrclksr** [comment]
Hello @schijtreiger,

thank you for the nice feedback and the problem report. I will look at it soon.

**Comment by mrclksr** [comment]
Sorry for the delay. https://github.com/mrclksr/DSBLogoutmgr/commit/ce1c7353f03ab1704a6bf1a7cb7494ed827d474b should fix the issue.

**Comment by schijtreiger** [comment]
That's quite alright, we all have our busy lives. I shall try the fix shortly!

**Comment by schijtreiger** [comment]
Confirmed 100% functionality!
FreeBSD 13.0-CURRENT FreeBSD 13.0-CURRENT r344612 amd64

I will be doing a buildworld today & bring this machine up to latest SVN base, I will report back to double-confirm functionality.
Thanks for the effort!

**Comment by mrclksr** [comment]
Excellent! Thank you.

**Comment by schijtreiger** [comment]
Confirmed 100% functional on FreeBSD 13.0-CURRENT FreeBSD 13.0-CURRENT r345014 amd64 1300014
Thanks again!

**Comment by mrclksr** [comment]
Great! Thank you for taking the time.
